### ISSUE TITLE
Transitioning to different route in Modal's onHide locks window scroll

### ISSUE THREAD

**Issue by caktux** [react-bootstrap/react-bootstrap#1137]
Issue was introduced between 0.24.0 and 0.24.1 while using react-router's transitionTo in a Modal's onHide. Scrolling locks up without any error, but resizing the window throws this:
```
Uncaught TypeError: Cannot read property 'scrollHeight' of null
    _getStyles @ Modal.js:499 --> var scrollHt = node.scrollHeight;
    handleWindowResize @ Modal.js:443
```
It seems the modal's own transition no longer handles having its component removed from the DOM, which is to be expected when closing a modal is supposed to take you to a different route.

**Comment by sreedhap** [comment]
I faced a similar problem.I guess, this is because the animation doesn't complete, and the transition leaves the body noscroll style. What worked for me is : transitioning after a timeout of 200ms or so, or set animation as false in the Modal.

**Comment by droberts84** [comment]
I was just bitten by the same issue, although not with react-router.  It seems if you change the `show` prop from `false` to `true` and back to `false` in a short period, you lose the scrollbar.

**Comment by luisincrespo** [comment]
Having the same issue here. Anyone has encountered a fix?

**Comment by droberts84** [comment]
I just disabled animation on the modal

**Comment by zallek** [comment]
Having the same problem

**Comment by taion** [comment]
Fixed by https://github.com/react-bootstrap/react-overlays/pull/33

**Comment by jquense** [comment]
Ahhh yes here is that issue, couldn't find it before

**Comment by jareware** [comment]
Doesn't look like this made the cut for `v0.28.1`, right?

**Comment by taion** [comment]
Well, it's a separate package. We don't lock down the version range for react-overlays very much either.

**Comment by jareware** [comment]
Oh, right, sorry!

````
$ npm list
...
├─┬ react-bootstrap@0.28.1
...
│ ├─┬ react-overlays@0.5.4
```

But I'm still getting

    Uncaught TypeError: Cannot read property 'scrollHeight' of null (Modal.js:267)

which is [this line](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L203).

Would you consider just prepending

```js
if (!node) {
  return {};
}
```

too naive of a fix?

**Comment by tingwei628** [comment]
I also found this error too

**Comment by taion** [comment]
Ah I see, we need to remove listeners on unmount as well.

**Comment by taion** [comment]
Let's move discussion to https://github.com/react-bootstrap/react-bootstrap/issues/1538.
