### ISSUE TITLE
Overlay trigger does not trigger when child button is disabled

### ISSUE THREAD

**Issue by smith-kyle** [react-bootstrap/react-bootstrap#1588]
An overlay trigger that wraps a button with a prop of `disabled` will not show overlay on hover. Not sure if this is considered a bug or a feature. In my specific case I'd like to disable a button and then give the reason on hover.

Displays overlay:
```javascript
<OverlayTrigger
  overlay={<Tooltip>Some overlay</Tooltip>}>
  <Button>Some button</Button>
</OverlayTrigger>
```

Does **not** display overlay:
```javascript
<OverlayTrigger
  overlay={<Tooltip>Some overlay</Tooltip>}>
  <Button disabled>Some button</Button>
</OverlayTrigger>
```

**Comment by jquense** [comment]
Yeah mouse events don't fire on disabled elements, so `hover` is going to fail there. Instead wrap your button in a span or other inline element. See also this note about it here: http://getbootstrap.com/javascript/#tooltips

**Comment by smith-kyle** [comment]
Thanks for the lightening fast response! :zap:

**Comment by jquense** [comment]
just happened to be looking at it :P

**Comment by tmcf** [comment]
This thread pointed me in the right direction to get this working for my use case. JSBin here: http://jsbin.com/midixo/edit in case its of use to anyone.

**Comment by jarone** [comment]
Thanks @jquense and @tmcf that was driving me crazy!

**Comment by caseprince** [comment]
This can also be solved with CSS:
`pointer-events: all;`
 This seems a little cleaner than polluting your markup?

**Comment by afc163** [comment]
@tmcf Thx, I follow you demo and made a workaround for [antd](http://github.com/ant-design/ant-design/)'s Tooltip: https://github.com/ant-design/ant-design/pull/4865

**Comment by pastaclub** [comment]
Here's a component that does the work-around: [react-bootstrap-tooltip-button](https://github.com/pastaclub/react-bootstrap-tooltip-button)

Wrapping a button in a `<div>` breaks the bootstrap styling for ButtonGroup and ButtonToolbar because those rules expect a button, not a div. This component fixes that as well.

**Comment by agrakhov** [comment]
@tmcf thanks a lot, spent a couple of hours on this problem.

**Comment by mortoray** [comment]
Alas, I'm unable to get the div wrapping solution to work. The disabled button is still not sending events. I've tried several options, and all I can get to work is not specifying disabled. :(

**Comment by simarsenault** [comment]
For my fellow Googlers: I wasn't able to make it work with either wrapping the `button` inside a `span`/`div` or the CSS `pointer-events: all;`. However, I made it work by creating a `div` with `position: absolute` above the button:

```typescript
public render(): JSX.Element {
	const overlay: JSX.Element = <Popover id={`overlay`}>
		<Popover.Content>
			Hello :)
		</Popover.Content>
	</Popover>;
	
	return <div>
		<OverlayTrigger placement="auto" overlay={overlay}>
			<div style={{ position: "absolute", top: "0", left: "0", width: "100%", height: "100%", cursor: "not-allowed", zIndex: 2 }}/>
		</OverlayTrigger>
		
		<MyCustomButton
			...
		/>
	</div>
}

```

**Comment by FlorianCassayre** [comment]
It seems something has changed in the newer versions that broke the old trick. @simarsenault's suggested workaround does the job (thanks for that by the way!), but is definitely far from optimal. Until someone finds a better alternative perhaps it is best to reopen the issue, WDYT?

**Comment by saurabhchauhan98** [comment]
Find the solution here in the official doc: https://react-bootstrap.github.io/components/overlays/#disabled-elements

> As a workaround, you’ll want to trigger the overlay from a wrapper <div> or <span> and override the pointer-events on the disabled element.

```


import Button from 'react-bootstrap/Button';
import OverlayTrigger from 'react-bootstrap/OverlayTrigger';
import Tooltip from 'react-bootstrap/Tooltip';

function DisabledExample() {
  return (
    <OverlayTrigger overlay={<Tooltip id="tooltip-disabled">Tooltip!</Tooltip>}>
      <span className="d-inline-block">
        <Button disabled style={{ pointerEvents: 'none' }}>
          Disabled button
        </Button>
      </span>
    </OverlayTrigger>
  );
}

export default DisabledExample;
```

**Comment by agas0077** [comment]
Don't know if it's the issue here, but I managed to make the tooltip appear only if the button is disabled. I use it to show user the he needs to become online to push the button if one is offline.
```
import { Button, OverlayTrigger, Tooltip } from "react-bootstrap";

export default function SubmitButton(props) {
  const { tooltipText, ...newProps } = props;

  return (
    <OverlayTrigger
      trigger="click"
      overlay={
        props.disabled ? (
          <Tooltip id="tooltip-disabled">{tooltipText}</Tooltip>
        ) : (
          <></>
        )
      }
    >
      <span className="d-inline-block">
        <Button {...newProps} style={{ pointerEvents: "none" }}>
          Disabled button
        </Button>
      </span>
    </OverlayTrigger>
  );
}
```
