### ISSUE TITLE
Compatibility with React v15

### ISSUE THREAD

**Issue by mjw56** [react-bootstrap/react-bootstrap#1708]
Hi,

Sorry if this is a dup, I looked around but did not see this mentioned. 

I upgraded react to [v15 rc2](https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html) and it is breaking with below error:

![image](https://cloud.githubusercontent.com/assets/161528/13899715/5bf8b280-edcb-11e5-804e-370ca4b45e8b.png)

I believe it is related to jquense/uncontrollable#9

It looks like it has been fixed, it just needs to be published and updated in this repo.

Just wanted to add this as a tracking issue.

Thanks

**Comment by cchamberlain** [comment]
@mjw56 - I was getting the same issue, I published a new version with updated uncontrollable dependency that fixes the issue temporarily - https://www.npmjs.com/package/react-bootstrap-15

**Comment by taion** [comment]
@jquense Can you cut a new uncontrollable release?

**Comment by jquense** [comment]
I will do it first thing tomorrow

**Comment by taion** [comment]
Looks like uncontrollable 3.2.3 is out.

**Comment by DeodorantMan** [comment]
I'm trying to run React 15. I have the latest react-bootstrap and I see uncontrollable 3.2.3 as a dependency. 
Still getting the error: `createUncontrollable.js?4c7d:31 Uncaught TypeError: Cannot read property 'propTypes' of undefined`
Any help would be appreciated. Thanks

**Comment by taion** [comment]
You probably need to reinstall. Everything already works – the docs page is already on React 15.

**Comment by taylorqj** [comment]
@taion this fixed it for me, thanks.

> createUncontrollable.js?4c7d:31 Uncaught TypeError: Cannot read property 'propTypes' of undefined

**Comment by DeodorantMan** [comment]
@taion I was playing around with getting this to work and this is what I came up with.
I normally run the long term support version of Node 4.4.2
When I install the latest react-bootstrap using Node 4.4.2, and I have React 15 installed I get:
```
npm ERR! peerinvalid The package react@15.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap@0.29.0-alpha.2 wants react@>=0.14.0
```
I found a solution by upgrading to Node version 5.10 and everything works fine, however I would like to stick to Node 4 until the next long term support version comes out.

**Comment by dtschust** [comment]
@DeodorantMan I'm also seeing the peerInvalid issue you're seeing, using npm2. Have you found a solution by chance?
