### ISSUE TITLE
Accordion not collapsing completely

### ISSUE THREAD

**Issue by ayushSindhwani** [react-bootstrap/react-bootstrap#3837]
## Describe the bug

A panel once open doesn't close when clicked on again.

## To Reproduce

1. Install react-bootstrap (1.0.0-beta.8) and bootstrap (4.3.1)
2. Add the Accordion component
3. Open a panel by clicking on it
4. Try to close the **same** panel by clicking on it again

## Reproducible Example

https://codesandbox.io/s/gifted-dew-6gbl5?fontsize=14

## Expected behaviour

Using the React dev tools on the react-bootstrap official Accordion page, I noticed that the Context.Provider's "value" prop changes to "null" in a fully collapsed state. However, this is not happening in my app as well as in the example provided above.

## Screenshots

My app:

![Screenshot from 2019-05-27 12-07-39](https://user-images.githubusercontent.com/40791590/58400876-f5845780-8079-11e9-9aa1-af0c55a07dab.png)

react-bootstrap Accordion documentation page:

![Screenshot from 2019-05-27 12-09-17](https://user-images.githubusercontent.com/40791590/58400882-fa490b80-8079-11e9-9316-ca6eef03ce35.png)

## Environment (please complete the following information)

- Operating System: Ubuntu 18.04
- Browser Version: Chrome 74
- React-Bootstrap Version: 1.0.0-beta.8
- Bootstrap Version: 4.3.1

**Comment by taion** [comment]
this was fixed in https://github.com/react-bootstrap/react-bootstrap/pull/3781

**Comment by ROODAY** [comment]
When will yarn be updated with this release? At the moment it's still shipping 1.0.0-beta.8 instead of beta.9

**Comment by taion** [comment]
beta 8 was tagged as `latest` for some reason. i tagged beta 9 as `latest`. but it was published and has been up

**Comment by DecolipAkira** [comment]
This problem still does not continue in the latest version.

When will it be corrected?
