### ISSUE TITLE
Add React 17 support

### ISSUE THREAD

**Issue by mesiarm** [react-bootstrap/react-bootstrap#5540]
Can you please add React 17 support?

**Comment by kyletsang** [comment]
React 17 already works.  Are you running into problems?

**Comment by mesiarm** [comment]
I´m giving error: 

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @restart/hooks@0.3.25
npm ERR! node_modules/@restart/hooks
npm ERR!   @restart/hooks@"^0.3.21" from react-bootstrap@1.4.0
npm ERR!   node_modules/react-bootstrap
npm ERR!     react-bootstrap@"^1.4.0" from the root project
npm ERR!   @restart/hooks@"^0.3.25" from react-overlays@4.1.1
npm ERR!   node_modules/react-overlays
npm ERR!     react-overlays@"^4.1.0" from react-bootstrap@1.4.0
npm ERR!     node_modules/react-bootstrap
npm ERR!       react-bootstrap@"^1.4.0" from the root project

**Comment by kyletsang** [comment]
Need to update the peer deps in @restart/hooks

**Comment by smartcdoane** [comment]
Besides that peer dep warning, I'm also getting conflicting TypeScript type definitions causing compilation failures.

It seems to be caused by react-bootstrap including a direct (non dev) dependency on `@types/react`. Is this something that can be moved to `devDependencies` or `peerDependencies` so it won't cause compilation errors for clients?

I'm receiving the following error upon updating to react 17:
```
node_modules/@types/react/index.d.ts(2981,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
node_modules/react-bootstrap/node_modules/@types/react/index.d.ts(2982,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
[...]
```
Plus many many more conflicting type errors of the same nature, all originating from `node_modules/react-bootstrap/node_modules/@types/react/index.d.ts`

My relevant `package.json` deps. All installed via npm.
```
"devDependencies": {
     "@types/react": "17.0.0",
     "@types/react-dom": "17.0.0"
},
"dependencies": {
    "typescript": "4.1.2",
    "react-bootstrap": "1.4.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
}
```

**Comment by hueter** [comment]
Also getting the same error as @smartcdoane , I'm not able to upgrade packages in my repo because of the type collisions

`node_modules/react-bootstrap/node_modules/@types/react/index.d.ts:2982:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.`

**Comment by kyletsang** [comment]
The `@types/react` issue is already fixed.  I think the only thing left outstanding is the react 17 peer dep issue in restart/hooks.

Anyways, if you want to work around the types issue, you can add `skipLibCheck: true` in your tsconfig.

**Comment by jquense** [comment]
@kyletsang what do you need me to do in restart/hooks?

**Comment by kyletsang** [comment]
@jquense can you merge https://github.com/react-restart/hooks/pull/42 and make a release?  Thanks!

**Comment by jquense** [comment]
done! sorry for dropping the ball here

**Comment by smartcdoane** [comment]
Ah, I totally missed that fix for react types. I was too focused on `1.4.0`! Apologies. We'll wait for a merge + release of react-bootstrap to fix that.

Thanks for your response on this.

**Comment by kyletsang** [comment]
> 
> 
> done! sorry for dropping the ball here

Thanks @jquense

**Comment by hueter** [comment]
hmm the upstream fix didn't fix the type errors for me but I was able to resolve my type errors by adding 

```
  "resolutions": {
    "@types/react": "17.0.0"
  },
```

to `package.json` to force all the dependencies to use those type definitions.

(for context I'm using `yarn`)

**Comment by kyletsang** [comment]
`@types/react` errors will be fixed in the next release of react-bootstrap

**Comment by kyletsang** [comment]
Avail in 1.4.3
