### ISSUE TITLE
OverlayTrigger trigger='click' is being closed when rootClose==true

### ISSUE THREAD

**Issue by luisrudge** [react-bootstrap/react-bootstrap#802]
Can anyone help me with this issue?

![popover closing](https://cloud.githubusercontent.com/assets/941075/8048136/52ac8742-0e24-11e5-8949-60b5b5cace8c.gif)

**Comment by taion** [comment]
Do you have a code repro?

Main thing this could likely be is that rootClose looks for clicks outside the popover element. If you replace the popover element entirely, then the existing check does the wrong thing.

**Comment by luisrudge** [comment]
@taion yeah. I was thinking something like that. Because it only happens when I click in a date of the next month, which replaces almost the entire calendar component.

**Comment by taion** [comment]
Okay, looking more closely at typical context menu style behavior, it really should be `onMouseDown` in the handler anyway, which would probably fix the behavior here.

**Comment by taion** [comment]
Hmm, except that's not what Bootstrap dropdowns do.

Any opinions what the correct behavior here is?

**Comment by luisrudge** [comment]
well, I think that if you're clicking anywhere inside the popover, it shouldn't close at all.

**Comment by taion** [comment]
The problem is that because you're replacing the popover entirely, your click is no longer landing inside the popover, since the old iteration of the popover is gone by the time that click is processed. Switching to mousedown would make life easier.

**Comment by luisrudge** [comment]
how do I try with the mousedown?

**Comment by luisrudge** [comment]
@taion any thoughts?

**Comment by jquense** [comment]
In this particular use case I think the problem is that "click outside" is the wrong way to handle it (just an opinion from making a bunch of inputs like this). I would turn off rootClose, and handle closing the popup when your date "widget" loses focus (ie. focus moves from the input or the popover to something else). If you really need finer toothed control over it I don't know that the popover is the right tool for the job here, as it is mostly designed to handle simple content.

**Comment by luisrudge** [comment]
@jquense if I remove rootClose, how do I manually close the popover?

**Comment by jquense** [comment]
The comonent child of `OverlayTrigger`is given a a hide prop it can call, or (uglier) actually call the `.hide()` method on the overlay trigger instance. `this.refs.overlayTrigger.hide()`

**Comment by taion** [comment]
It's actually always injected as `props.onRequestHide` on the overlay... same regardless of whether `rootClose` is used.

**Comment by AlexKVal** [comment]
Superceded by #855

**Comment by taion** [comment]
This was actually fixed by #839.

**Comment by taion** [comment]
(but only for v0.24)

**Comment by AlexKVal** [comment]
Nice. Thank you @taion :cherries:

**Comment by MiroslavBeno** [comment]
Hey, I still have this problem, that popover is closed, when I click simple input inside of it. v0.28.5
